### ISSUE TITLE
static_admin/js/app.js – Ссылки на статику модулей

### ISSUE THREAD

**Issue by latur** [phact-cmf/default#2]
[Ссылки на статику модулей](https://github.com/phact-cmf/default/blob/29e4693eb948776d502bf13b1e01b113382409e1/static_admin/js/app.js#L24-L27) из старой версии факта не верны, там уже ничего нет, заменить бы на что-то вроде:

```js
/* Files module */
require('../../vendor/phact-cmf-modules/files/static/filesfield/filesfield');
/* Editor module */
require('../../vendor/phact-cmf-modules/Editor/static/fileman/fileman');
```

Или красивее, прописав алиас `../../vendor/phact-cmf-modules/` в конфиг вебпака

**Comment by AntonOkulov** [comment]
Теперь статика в админку цепляется из static_modules
